<a href="https://colab.research.google.com/github/walnashgit/RL-Bellman-Basic/blob/main/ERAV3_s19_RL_Bellmanbasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


def value_iteration(threshold=1e-4, gamma=1.0):
    grid_size = 4
    num_states = grid_size * grid_size
    V = np.zeros(num_states)  # Initialize value function to 0 for all states
    actions = [(-1, 0), (1, 0), (0, -1), (0, 1)]  # Up, Down, Left, Right

    while True:
        delta = 0
        new_V = np.copy(V)

        for state in range(num_states):
            if state == num_states - 1:  # Terminal state
                continue

            row, col = divmod(state, grid_size)
            value_sum = 0

            for action in actions:
                new_row, new_col = row + action[0], col + action[1]

                if 0 <= new_row < grid_size and 0 <= new_col < grid_size:
                    next_state = new_row * grid_size + new_col
                else:
                    next_state = state  # If out of bounds, stay in the same state

                reward = -1  # Reward for each move
                value_sum += (1 / 4) * (reward + gamma * V[next_state])

            new_V[state] = value_sum
            delta = max(delta, abs(new_V[state] - V[state]))

        V = new_V
        if delta < threshold:
            break

    return V.reshape((grid_size, grid_size))


In [3]:
  optimal_values = value_iteration()
  print(optimal_values)

[[-59.42367735 -57.42387125 -54.2813141  -51.71012579]
 [-57.42387125 -54.56699476 -49.71029394 -45.13926711]
 [-54.2813141  -49.71029394 -40.85391609 -29.99766609]
 [-51.71012579 -45.13926711 -29.99766609   0.        ]]
